FROM node:20.6.1 as builder
RUN mkdir -p /app
WORKDIR /app
COPY . .
COPY .env /app/.env.production

RUN yarn install --force --network-timeout 600000 && yarn build

FROM node:20.6.1-slim
WORKDIR /app
COPY --from=builder /app /app 
EXPOSE 3000
LABEL base="false"
CMD ["yarn", "run" , "start"]
