export const bannedWords = [
  'Blood',
  'Bloodbath',
  'Crucifixion',
  'Bloody',
  'Flesh',
  'Bruises',
  'Car crash',
  'Corpse',
  'Crucified',
  'Cutting',
  'Decapitate',
  'Infested',
  'Gruesome',
  'Kill',
  'Infected',
  'Sadist',
  'Slaughter',
  'Teratoma',
  'Tryphophobia',
  'Wound',
  'Cronenberg',
  'Khorne',
  'Cannibal',
  'Cannibalism',
  'Visceral',
  'Guts',
  'Bloodshot',
  'Gory',
  'Killing',
  'Surgery',
  'Vivisection',
  'Massacre',
  'Hemoglobin',
  'Suicide',
  'Female Body Parts',
  'ahegao',
  'pinup',
  'ballgag',
  'Playboy',
  'Bimbo',
  'pleasure',
  'bodily fluids',
  'pleasures',
  'boudoir',
  'rule34',
  'brothel',
  'seducing',
  'dominatrix',
  'seductive',
  'erotic seductive',
  'fuck',
  'sensual',
  'Hardcore',
  'sexy',
  'Hentai',
  'Shag',
  'horny',
  'shibari (bondage in japanese)',
  'incest',
  'Smut',
  'jav',
  'succubus',
  'Jerk off king at pic',
  'thot',
  'kinbaku (bondage in Japanese)',
  'transparent',
  'submissive',
  'dominant',
  'nasty',
  'indecent',
  'legs spread',
  'cussing',
  'flashy',
  'twerk',
  'making love',
  'voluptuous',
  'naughty',
  'wincest',
  'orgy',
  'Sultry',
  'XXX',
  'Bondage',
  'Bdsm',
  'Dog collar',
  'Slavegirl',
  'Transparent and Translucent',
  'Arse',
  'Labia',
  'Ass',
  'Mammaries',
  'Human centipede',
  'Badonkers',
  'Minge (Slang for vag)',
  'Massive chests',
  'Big Ass',
  'Mommy Milker (milker or mommy is fine)',
  'Booba',
  'Nipple',
  'Booty',
  'Oppai (Japanese word for breasts)',
  'Bosom',
  'Melons (in bad sense)',
  'Bulging',
  'Coochie',
  'Head (in vulgar sense)',
  'Engorged',
  'Organs',
  'Breasts',
  'Ovaries',
  'Busty',
  'Penis',
  'Clunge (British slang for vagina)',
  'Phallus',
  'Crotch',
  'sexy female',
  'Dick (as in Moby-Dick)',
  'Skimpy',
  'Girth',
  'Thick',
  'Honkers',
  'Vagina',
  'Hooters',
  'Veiny',
  'Knob',
  'Seductress',
  'Shaft',
  'no clothes',
  'Speedo',
  'au naturale',
  'no shirt',
  'bare chest',
  'nude',
  'barely dressed',
  'bra',
  'risqué',
  'clear',
  'scantily',
  'clad',
  'cleavage',
  'stripped',
  'full frontal unclothed',
  'invisible clothes',
  'wearing nothing',
  'lingerie with no shirt',
  'naked',
  'without clothes on',
  'negligee',
  'zero clothes',
  'Taboo',
  'Fascist',
  'Nazi',
  'Prophet Mohammed',
  'Slave',
  'Coon',
  'Honkey',
  'Arrested',
  'Jail',
  'Handcuffs',
  'Drugs',
  'Cocaine',
  'Heroin',
  'Meth',
  'Crack',
  'Torture',
  'Disturbing',
  'Farts, Fart',
  'Poop',
  'Warts',
  'Xi Jinping',
  'Shit',
  'Pleasure',
  'Errect',
  'Big Black',
  'Brown pudding',
  'Bunghole',
  'Vomit',
  'Voluptuous',
  'Seductive',
  'Sperm',
  'Hot',
  'Sexy',
  'Plebeian',
  'Sensored',
  'Censored',
  'Uncouth',
  'Silenced',
  'Deepfake',
  'Inappropriate',
  'Pus',
  'Waifu',
  'mp5',
  'Succubus',
  '1488',
  'Surgery',
  'trump',
  'kamala',
  'elections',
  'biden',
  'USA elections ',
  'donald trumo',
  'kamala harris',
  '911'
]

export const checkBannedWords = (_str: string) => {
  const str = _str || ''

  const normalizedStr = str.toLowerCase().trim()
  const bannedWordsLowerCase = bannedWords.map((word) => word.toLowerCase())
  // Function to check if a word is surrounded by word boundaries
  const isWholeWord = (str: string, word: string) => {
    const regex = new RegExp(`\\b${word}\\b`, 'i')
    return regex.test(str)
  }
  // Function to find all banned words in the string
  const findBannedWords = (str: string): string[] => {
    return bannedWordsLowerCase.filter((word) => isWholeWord(str, word))
  }

  // Find all banned words in the normalized string
  const foundBannedWords = findBannedWords(normalizedStr)

  // If banned words are found, return them as an array
  // Otherwise, return false
  if (foundBannedWords.length > 0) {
    return Array.from(new Set(foundBannedWords))
  }

  // Check if any banned word is present as a whole word
  return bannedWordsLowerCase.some((word) => isWholeWord(normalizedStr, word))
}
