export enum GET_THREAD_TYPE {
  NEW_THREADS = 'NEW_THREADS',
  NEW_COINS = 'NEW_COINS',
  FOLLOWING = 'FOLLOWING',
  TRENDING = 'TRENDING',
  LIKED = 'LIKED',
  TRACKING = 'TRACKING',
  BOUGHT = 'BOUGHT',
  CERTIFIED = 'CERTIFIED',
  PORTFOLIO = 'PORTFOLIO',
  AI_COIN = 'AI_COIN',
  AI_TRENDING = 'AI_TRENDING'
}
export enum SORT_FIELDS {
  PUSH_ORDER_DESC = 'lastTradeAt:-1',
  CREATED_AT_DESC = 'createdAt:-1',
  MARKET_CAP_DESC = 'currentMarketcapBySol:-1',
  LIVE_AND_TRADING_DESC = 'reachedMarketcap:-1',
  REPLIES_COUNT_DESC = 'repliesCount:-1',
  CURVE_PERCENT_DESC = 'curvePercent:-1',
  ADD_POOL_AT_DESC = 'addPoolAt:-1',
  HIT_TOP_AT_DESC = 'hitTopTimestamp:-1'
}
// - Newborns: sortBy: sortBy: SORT_FIELDS.CREATED_AT_DESC, type: GET_THREAD_TYPE.NEW_COINS | GET_THREAD_TYPE.TRACKING |  GET_THREAD_TYPE.BOUGHT
// - TopRunner: sortBy: sortBy: SORT_FIELDS.CURVE_PERCENT_DESC, type: GET_THREAD_TYPE.NEW_COINS | GET_THREAD_TYPE.TRACKING |  GET_THREAD_TYPE.BOUGHT
// - Trending Threads: type: GET_THREAD_TYPE.TRENDING
// - Push Order:  sortBy: SORT_FIELDS.PUSH_ORDER_DESC, type: GET_THREAD_TYPE.NEW_COINS | GET_THREAD_TYPE.TRACKING |  GET_THREAD_TYPE.BOUGHT

export enum CURVE_PERCENT {
  TOP_RUNNER = '60_100',
  CERTIFIED = '100'
}

export enum LIQUIDITY_DEX {
  RAYDIUM = 'RAYDIUM',
  METEORA = 'METEORA'
}
